import 'package:flutter/material.dart';
import '../../core/theme/app_colors.dart';
import '../../core/routes/app_routes.dart';
import '../../models/tool_item.dart';

class ToolsScreen extends StatelessWidget {
  const ToolsScreen({super.key});

  static final List<ToolCategory> _categories = [
    ToolCategory(
      id: 'air-distribution',
      sortOrder: 1,
      name: 'Air Distribution',
      emoji: '🌬️',
      icon: Icons.air,
      accent: const Color(0xFF00BFA5),
      imageAsset: 'assets/images/tools/air_distribution.png',
      tools: [
        ToolItem(
          id: 'duct-calculator',
          categoryId: 'air-distribution',
          title: 'Duct Calculator',
          desc: 'Thiết kế ống gió tròn, chữ nhật theo lưu lượng CFM.',
          icon: Icons.air,
          color: const Color(0xFF00BFA5),
          route: AppRoutes.ductSizer,
          isReady: true,
          standard: 'SMACNA / ASHRAE',
          capabilities: [
            'round-duct-sizing',
            'rectangular-duct-sizing',
            'velocity-method',
            'equal-friction',
          ],
          supportedUnits: ToolUnitSystem.both,
        ),
        ToolItem(
          id: 'duct-pressure-loss',
          categoryId: 'air-distribution',
          title: 'Duct Pressure Loss',
          desc: 'Tính tổn thất áp suất đường ống gió.',
          icon: Icons.compress,
          color: const Color(0xFF26C6DA),
          route: AppRoutes.ductPressureLoss,
          isReady: true,
          standard: 'Darcy-Weisbach / ASHRAE',
          capabilities: [
            'friction-loss',
            'fitting-loss',
            'velocity',
            'reynolds',
          ],
        ),
        ToolItem(
          id: 'equal-friction-duct-sizer',
          categoryId: 'air-distribution',
          title: 'Equal Friction Duct Sizer',
          desc: 'Thiết kế theo phương pháp Equal Friction.',
          icon: Icons.balance,
          color: const Color(0xFF00ACC1),
          route: AppRoutes.equalFriction,
          isReady: true,
          standard: 'SMACNA',
          capabilities: [
            'equal-friction',
            'round-sizing',
            'rectangular-sizing',
          ],
        ),
        ToolItem(
          id: 'velocity-duct-sizer',
          categoryId: 'air-distribution',
          title: 'Velocity Duct Sizer',
          desc: 'Thiết kế theo phương pháp Velocity.',
          icon: Icons.speed,
          color: const Color(0xFF0097A7),
          route: AppRoutes.velocityReduction,
          isReady: true,
          standard: 'SMACNA',
          capabilities: [
            'velocity-method',
            'round-sizing',
            'rectangular-sizing',
          ],
        ),
        ToolItem(
          id: 'duct-fitting-loss',
          categoryId: 'air-distribution',
          title: 'Duct Fitting Loss',
          desc: 'Tổn thất qua co, cút, tê, van...',
          icon: Icons.turn_right,
          color: const Color(0xFF00838F),
          route: AppRoutes.fittingLoss,
          isReady: true,
          standard: 'SMACNA',
          capabilities: [
            'elbow-loss',
            'tee-loss',
            'fitting-coefficient',
            'K-value',
          ],
        ),
        ToolItem(
          id: 'air-velocity-calculator',
          categoryId: 'air-distribution',
          title: 'Air Velocity Calculator',
          desc: 'Tính vận tốc gió trong ống.',
          icon: Icons.toys,
          color: const Color(0xFF006064),
          route: AppRoutes.airVelocityCalculator,
          isReady: true,
          capabilities: [
            'velocity-from-cfm',
            'diameter-to-velocity',
            'round-duct',
          ],
        ),
        ToolItem(
          id: 'airflow-calculator',
          categoryId: 'air-distribution',
          title: 'Airflow Calculator',
          desc: 'Tính lưu lượng gió CFM / m³/h.',
          icon: Icons.wind_power,
          color: const Color(0xFF00B8D4),
          route: AppRoutes.airflowCalculator,
          isReady: true,
          capabilities: ['flow-rate', 'velocity', 'ach', 'cfm-to-m3h'],
        ),
        ToolItem(
          id: 'ach-calculator',
          categoryId: 'air-distribution',
          title: 'Air Change Calculator (ACH)',
          desc: 'Số lần thay đổi không khí/giờ.',
          icon: Icons.refresh,
          color: const Color(0xFF00BCD4),
          route: AppRoutes.achCalculator,
          isReady: true,
          capabilities: ['ach-to-cfm', 'cfm-to-ach', 'room-volume'],
        ),
        ToolItem(
          id: 'diffuser-selector',
          categoryId: 'air-distribution',
          title: 'Diffuser Selector',
          desc: 'Chọn miệng gió phù hợp.',
          icon: Icons.scatter_plot,
          color: const Color(0xFF009688),
          route: AppRoutes.diffuserSelection,
          isReady: true,
          standard: 'ASHRAE',
          capabilities: [
            'diffuser-type',
            'throw-distance',
            'neck-velocity',
            'NC-rating',
          ],
        ),
        ToolItem(
          id: 'grille-selector',
          categoryId: 'air-distribution',
          title: 'Grille Selector',
          desc: 'Chọn cửa gió hồi / cấp.',
          icon: Icons.grid_view,
          color: const Color(0xFF00897B),
          route: AppRoutes.grilleSelection,
          isReady: true,
          standard: 'ASHRAE',
          capabilities: ['grille-type', 'free-area', 'face-velocity'],
        ),
        ToolItem(
          id: 'vav-box-sizing',
          categoryId: 'air-distribution',
          title: 'VAV Box Sizing',
          desc: 'Chọn hộp VAV theo lưu lượng.',
          icon: Icons.dashboard_customize,
          color: const Color(0xFF00796B),
          route: AppRoutes.vavBoxSizing,
          isReady: true,
          capabilities: ['VAV-sizing', 'cooling-CFM', 'min-CFM', 'reheat'],
        ),
        ToolItem(
          id: 'fan-selection',
          categoryId: 'air-distribution',
          title: 'Fan Selection',
          desc: 'Chọn quạt theo cột áp và lưu lượng.',
          icon: Icons.toys_outlined,
          color: const Color(0xFF00695C),
          route: AppRoutes.fanSelection,
          isReady: true,
          capabilities: [
            'fan-power',
            'RPM',
            'efficiency',
            'pressure-classification',
          ],
        ),
      ],
    ),
    ToolCategory(
      id: 'refrigeration',
      sortOrder: 2,
      name: 'Refrigeration',
      emoji: '❄️',
      icon: Icons.ac_unit,
      accent: const Color(0xFF388AF6),
      imageAsset: 'assets/images/tools/refrigeration.png',
      tools: [
        ToolItem(
          id: 'pt-chart',
          categoryId: 'refrigeration',
          title: 'PT Chart',
          desc: 'Biểu đồ Áp suất – Nhiệt độ các môi chất lạnh.',
          icon: Icons.thermostat,
          color: const Color(0xFF388AF6),
          route: AppRoutes.ptChart,
          isReady: true,
          capabilities: ['PT-chart', 'refrigerant-properties', 'saturation'],
        ),
        ToolItem(
          id: 'superheat-calculator',
          categoryId: 'refrigeration',
          title: 'Superheat Calculator',
          desc: 'Tính Superheat để chẩn đoán hệ thống.',
          icon: Icons.trending_up,
          color: const Color(0xFFFF9800),
          route: AppRoutes.superheat,
          isReady: true,
          capabilities: ['superheat', 'subcool', 'diagnostics'],
        ),
        ToolItem(
          id: 'subcooling-calculator',
          categoryId: 'refrigeration',
          title: 'Subcooling Calculator',
          desc: 'Tính Subcooling kiểm tra dàn ngưng.',
          icon: Icons.trending_down,
          color: const Color(0xFFFFA726),
          route: AppRoutes.subcoolingCalculator,
          isReady: true,
          capabilities: ['subcooling', 'condenser-check'],
        ),
        ToolItem(
          id: 'refrigerant-charge-calculator',
          categoryId: 'refrigeration',
          title: 'Refrigerant Charge Calculator',
          desc: 'Tính lượng gas nạp thêm / bổ sung.',
          icon: Icons.local_gas_station,
          color: const Color(0xFFFF7043),
          route: null,
          isReady: false,
          capabilities: ['charge-calculation', 'refrigerant-mass'],
        ),
        ToolItem(
          id: 'refrigerant-pipe-sizer',
          categoryId: 'refrigeration',
          title: 'Refrigerant Pipe Sizer',
          desc: 'Chọn kích thước ống môi chất lạnh.',
          icon: Icons.plumbing,
          color: const Color(0xFFFF5722),
          route: null,
          isReady: false,
          capabilities: [
            'pipe-sizing',
            'suction-line',
            'liquid-line',
            'discharge-line',
          ],
        ),
        ToolItem(
          id: 'pressure-converter',
          categoryId: 'refrigeration',
          title: 'Pressure Converter',
          desc: 'Chuyển đổi áp suất (PSI, Bar, kPa, MPa, inHg, mmHg).',
          icon: Icons.swap_vert,
          color: const Color(0xFF42A5F5),
          route: AppRoutes.pressureConverter,
          isReady: true,
          capabilities: ['pressure-conversion', 'PSI', 'Bar', 'kPa', 'MPa'],
        ),
        ToolItem(
          id: 'saturation-temperature',
          categoryId: 'refrigeration',
          title: 'Saturation Temperature',
          desc: 'Tra nhiệt độ bão hòa theo áp suất.',
          icon: Icons.device_thermostat,
          color: const Color(0xFF1E88E5),
          route: AppRoutes.saturationTemperature,
          isReady: true,
          capabilities: ['saturation-temp', 'pressure-to-temp'],
        ),
      ],
    ),
    ToolCategory(
      id: 'hydronic',
      sortOrder: 3,
      name: 'Hydronic',
      emoji: '💧',
      icon: Icons.water_drop,
      accent: const Color(0xFF2196F3),
      imageAsset: 'assets/images/tools/hydronic.png',
      tools: [
        ToolItem(
          id: 'pipe-sizer',
          categoryId: 'hydronic',
          title: 'Pipe Sizer',
          desc: 'Thiết kế đường ống nước theo lưu lượng.',
          icon: Icons.water,
          color: const Color(0xFF2196F3),
          route: AppRoutes.pipeSizer,
          isReady: true,
          capabilities: ['pipe-sizing', 'water-flow', 'velocity'],
        ),
        ToolItem(
          id: 'water-flow-calculator',
          categoryId: 'hydronic',
          title: 'Water Flow Calculator',
          desc: 'Tính lưu lượng nước qua ống.',
          icon: Icons.waves,
          color: const Color(0xFF1E88E5),
          route: AppRoutes.waterFlow,
          isReady: true,
          capabilities: ['flow-rate', 'velocity', 'GPM'],
        ),
        ToolItem(
          id: 'pipe-pressure-loss',
          categoryId: 'hydronic',
          title: 'Pipe Pressure Loss',
          desc: 'Tổn thất áp suất đường ống nước.',
          icon: Icons.horizontal_rule,
          color: const Color(0xFF1976D2),
          route: AppRoutes.pipePressureLoss,
          isReady: true,
          capabilities: ['pressure-loss', 'Darcy-Weisbach', 'friction'],
        ),
        ToolItem(
          id: 'pump-head-calculator',
          categoryId: 'hydronic',
          title: 'Pump Head Calculator',
          desc: 'Tính cột áp bơm yêu cầu.',
          icon: Icons.arrow_upward,
          color: const Color(0xFF1565C0),
          route: null,
          isReady: false,
          capabilities: ['pump-head', 'static-head', 'friction-head'],
        ),
        ToolItem(
          id: 'pump-selection',
          categoryId: 'hydronic',
          title: 'Pump Selection',
          desc: 'Chọn bơm theo lưu lượng và cột áp.',
          icon: Icons.water_damage,
          color: const Color(0xFF0D47A1),
          route: null,
          isReady: false,
          capabilities: ['pump-selection', 'efficiency', 'power'],
        ),
        ToolItem(
          id: 'expansion-tank-calculator',
          categoryId: 'hydronic',
          title: 'Expansion Tank Calculator',
          desc: 'Tính dung tích bình giãn nở.',
          icon: Icons.invert_colors,
          color: const Color(0xFF0277BD),
          route: null,
          isReady: false,
          capabilities: [
            'expansion-tank',
            'thermal-expansion',
            'closed-system',
          ],
        ),
      ],
    ),
    ToolCategory(
      id: 'load-psychrometrics',
      sortOrder: 4,
      name: 'Load & Psychrometrics',
      emoji: '🌡️',
      icon: Icons.thermostat_auto,
      accent: const Color(0xFFE91E63),
      imageAsset: 'assets/images/tools/load_psychrometrics.png',
      tools: [
        ToolItem(
          id: 'cooling-load-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Cooling Load Calculator',
          desc: 'Tính tải lạnh cho phòng / công trình.',
          icon: Icons.severe_cold,
          color: const Color(0xFFE91E63),
          route: null,
          isReady: false,
          capabilities: [
            'cooling-load',
            'sensible-load',
            'latent-load',
            'CLTD',
          ],
        ),
        ToolItem(
          id: 'heating-load-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Heating Load Calculator',
          desc: 'Tính tải sưởi cho phòng / công trình.',
          icon: Icons.local_fire_department,
          color: const Color(0xFFEC407A),
          route: null,
          isReady: false,
          capabilities: ['heating-load', 'heat-loss', 'U-value'],
        ),
        ToolItem(
          id: 'psychrometric-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Psychrometric Calculator',
          desc: 'Biểu đồ không khí ẩm tra cứu nhanh.',
          icon: Icons.bubble_chart,
          color: const Color(0xFFD81B60),
          route: null,
          isReady: false,
          capabilities: [
            'psychrometric-chart',
            'enthalpy',
            'humidity-ratio',
            'dew-point',
          ],
        ),
        ToolItem(
          id: 'dew-point-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Dew Point Calculator',
          desc: 'Tính điểm sương theo nhiệt độ & độ ẩm.',
          icon: Icons.water_drop_outlined,
          color: const Color(0xFFC2185B),
          route: AppRoutes.dewPointCalculator,
          isReady: true,
          capabilities: ['dew-point', 'condensation'],
        ),
        ToolItem(
          id: 'humidity-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Humidity Calculator',
          desc: 'Tính độ ẩm tương đối / tuyệt đối.',
          icon: Icons.opacity,
          color: const Color(0xFFAD1457),
          route: AppRoutes.humidityCalculator,
          isReady: true,
          capabilities: ['RH', 'humidity-ratio', 'wet-bulb'],
        ),
        ToolItem(
          id: 'enthalpy-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Enthalpy Calculator',
          desc: 'Tính enthalpy không khí ẩm.',
          icon: Icons.whatshot,
          color: const Color(0xFF880E4F),
          route: null,
          isReady: false,
          capabilities: ['enthalpy', 'psychrometrics'],
        ),
        ToolItem(
          id: 'fresh-air-calculator',
          categoryId: 'load-psychrometrics',
          title: 'Fresh Air Calculator',
          desc: 'Tính lưu lượng gió tươi theo người / diện tích.',
          icon: Icons.air_outlined,
          color: const Color(0xFFF06292),
          route: null,
          isReady: false,
          capabilities: ['OA', 'ventilation', 'per-person', 'per-area'],
        ),
      ],
    ),
    ToolCategory(
      id: 'conversion',
      sortOrder: 5,
      name: 'Conversion',
      emoji: '🔄',
      icon: Icons.swap_horiz,
      accent: const Color(0xFF9C27B0),
      imageAsset: 'assets/images/tools/conversion.png',
      tools: [
        ToolItem(
          id: 'hvac-unit-converter',
          categoryId: 'conversion',
          title: 'HVAC Unit Converter',
          desc: 'Chuyển đổi đơn vị HVAC: BTU/h, HP, kW, Tons...',
          icon: Icons.swap_horiz,
          color: const Color(0xFFE91E63),
          route: AppRoutes.unitConverter,
          isReady: true,
          capabilities: ['BTU', 'kW', 'HP', 'ton', 'W'],
        ),
        ToolItem(
          id: 'temperature-converter',
          categoryId: 'conversion',
          title: 'Temperature Converter',
          desc: 'Chuyển đổi °C, °F, K.',
          icon: Icons.thermostat,
          color: const Color(0xFFAB47BC),
          route: null,
          isReady: false,
          capabilities: ['C', 'F', 'K'],
        ),
        ToolItem(
          id: 'flow-converter',
          categoryId: 'conversion',
          title: 'Flow Converter',
          desc: 'Chuyển đổi CFM, m³/h, L/s, GPM.',
          icon: Icons.waves,
          color: const Color(0xFF8E24AA),
          route: null,
          isReady: false,
          capabilities: ['CFM', 'm3h', 'Ls', 'GPM'],
        ),
        ToolItem(
          id: 'velocity-converter',
          categoryId: 'conversion',
          title: 'Velocity Converter',
          desc: 'Chuyển đổi m/s, FPM, km/h.',
          icon: Icons.speed,
          color: const Color(0xFF7B1FA2),
          route: null,
          isReady: false,
          capabilities: ['ms', 'FPM', 'kmh'],
        ),
        ToolItem(
          id: 'power-converter',
          categoryId: 'conversion',
          title: 'Power Converter',
          desc: 'Chuyển đổi W, kW, HP, BTU/h.',
          icon: Icons.flash_on,
          color: const Color(0xFF6A1B9A),
          route: null,
          isReady: false,
          capabilities: ['W', 'kW', 'HP', 'BTU'],
        ),
        ToolItem(
          id: 'length-converter',
          categoryId: 'conversion',
          title: 'Length Converter',
          desc: 'Chuyển đổi mm, cm, m, inch, ft.',
          icon: Icons.straighten,
          color: const Color(0xFF4A148C),
          route: null,
          isReady: false,
          capabilities: ['mm', 'cm', 'm', 'inch', 'ft'],
        ),
      ],
    ),
    ToolCategory(
      id: 'electrical',
      sortOrder: 6,
      name: 'Electrical',
      emoji: '⚡',
      icon: Icons.electric_bolt,
      accent: const Color(0xFFFFC107),
      imageAsset: 'assets/images/tools/electrical.png',
      tools: [
        ToolItem(
          id: 'motor-current-calculator',
          categoryId: 'electrical',
          title: 'Motor Current Calculator',
          desc: 'Tính dòng điện động cơ 1 pha / 3 pha.',
          icon: Icons.electrical_services,
          color: const Color(0xFFFFB300),
          route: null,
          isReady: false,
          capabilities: [
            'motor-current',
            'single-phase',
            'three-phase',
            'ampere',
          ],
        ),
        ToolItem(
          id: 'cable-size-calculator',
          categoryId: 'electrical',
          title: 'Cable Size Calculator',
          desc: 'Tính tiết diện cáp theo dòng tải.',
          icon: Icons.cable,
          color: const Color(0xFFFFA000),
          route: null,
          isReady: false,
          capabilities: ['cable-sizing', 'ampacity', 'voltage-drop'],
        ),
        ToolItem(
          id: 'breaker-selector',
          categoryId: 'electrical',
          title: 'Breaker Selector',
          desc: 'Chọn CB (MCB/MCCB) phù hợp.',
          icon: Icons.toggle_on,
          color: const Color(0xFFFF8F00),
          route: null,
          isReady: false,
          capabilities: ['breaker', 'MCB', 'MCCB', 'overcurrent'],
        ),
        ToolItem(
          id: 'power-calculator',
          categoryId: 'electrical',
          title: 'Power Calculator',
          desc: 'Tính công suất điện 1 pha / 3 pha.',
          icon: Icons.power,
          color: const Color(0xFFFF6F00),
          route: null,
          isReady: false,
          capabilities: ['power', 'PF', 'single-phase', 'three-phase'],
        ),
      ],
    ),
    ToolCategory(
      id: 'service-commissioning',
      sortOrder: 7,
      name: 'Service & Commissioning',
      emoji: '📋',
      icon: Icons.assignment,
      accent: const Color(0xFF4CAF50),
      imageAsset: 'assets/images/tools/service_commissioning.png',
      tools: [
        ToolItem(
          id: 'service-checklist',
          categoryId: 'service-commissioning',
          title: 'Service Checklist',
          desc: 'Checklist bảo trì định kỳ hệ thống HVAC.',
          icon: Icons.checklist,
          color: const Color(0xFF66BB6A),
          route: null,
          isReady: false,
          capabilities: ['checklist', 'maintenance', 'inspection'],
        ),
        ToolItem(
          id: 'commissioning-report',
          categoryId: 'service-commissioning',
          title: 'Commissioning Report',
          desc: 'Biên bản chạy thử & nghiệm thu hệ thống.',
          icon: Icons.assignment_turned_in,
          color: const Color(0xFF4CAF50),
          route: null,
          isReady: false,
          capabilities: ['commissioning', 'acceptance', 'testing'],
        ),
        ToolItem(
          id: 'measurement-logger',
          categoryId: 'service-commissioning',
          title: 'Measurement Logger',
          desc: 'Ghi số liệu đo đạc tại hiện trường.',
          icon: Icons.note_add,
          color: const Color(0xFF43A047),
          route: null,
          isReady: false,
          capabilities: ['logger', 'field-data', 'measurement'],
        ),
        ToolItem(
          id: 'equipment-database',
          categoryId: 'service-commissioning',
          title: 'Equipment Database',
          desc: 'Cơ sở dữ liệu thiết bị HVAC.',
          icon: Icons.storage,
          color: const Color(0xFF388E3C),
          route: null,
          isReady: false,
          capabilities: ['database', 'equipment', 'specifications'],
        ),
        ToolItem(
          id: 'error-code-lookup',
          categoryId: 'service-commissioning',
          title: 'Error Code Lookup',
          desc: 'Tra mã lỗi các dòng điều hòa thông dụng.',
          icon: Icons.error_outline,
          color: const Color(0xFF2E7D32),
          route: null,
          isReady: false,
          capabilities: ['error-codes', 'troubleshooting', 'diagnostics'],
        ),
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgPrimary,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(
            Icons.arrow_back_ios_new,
            color: Colors.white,
            size: 20,
          ),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: const Text(
          'Công cụ kỹ thuật',
          style: TextStyle(
            color: Colors.white,
            fontSize: 18,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: true,
      ),
      body: GridView.builder(
        padding: const EdgeInsets.fromLTRB(16, 8, 16, 24),
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 2,
          mainAxisSpacing: 14,
          crossAxisSpacing: 14,
          childAspectRatio: 0.92,
        ),
        itemCount: _categories.length,
        itemBuilder: (context, index) {
          final category = _categories[index];
          return _CategoryCard(
            category: category,
            onTap: () => Navigator.pushNamed(
              context,
              AppRoutes.toolCategory,
              arguments: category,
            ),
          );
        },
      ),
    );
  }
}

class _CategoryCard extends StatelessWidget {
  final ToolCategory category;
  final VoidCallback onTap;

  const _CategoryCard({required this.category, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      borderRadius: BorderRadius.circular(20),
      onTap: onTap,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20),
        child: Stack(
          fit: StackFit.expand,
          children: [
            Image.asset(
              category.imageAsset,
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) {
                debugPrint(
                  '❌ ASSET FAIL: ${category.imageAsset}\n'
                  '   error: $error\n'
                  '   stack: $stackTrace',
                );
                return Container(
                  color: category.accent.withValues(alpha: 0.25),
                );
              },
            ),
            DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.black.withValues(alpha: 0.10),
                    Colors.black.withValues(alpha: 0.45),
                  ],
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(14),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        width: 42,
                        height: 42,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: Colors.black.withValues(alpha: 0.35),
                          border: Border.all(
                            color: Colors.white.withValues(alpha: 0.35),
                            width: 1,
                          ),
                        ),
                        child: Icon(
                          category.icon,
                          color: Colors.white,
                          size: 22,
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 8,
                          vertical: 3,
                        ),
                        decoration: BoxDecoration(
                          color: Colors.black.withValues(alpha: 0.45),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: Text(
                          '${category.tools.length}',
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 11,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const Spacer(),
                  Text(
                    category.name,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontWeight: FontWeight.bold,
                      height: 1.2,
                      shadows: [
                        Shadow(
                          color: Colors.black54,
                          blurRadius: 4,
                          offset: Offset(0, 1),
                        ),
                      ],
                    ),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 4),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: const [
                      Text(
                        'Mở',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      SizedBox(width: 4),
                      Icon(
                        Icons.arrow_forward_ios,
                        size: 11,
                        color: Colors.white,
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
